import java.util.Scanner;

/* Psuedocode

Initialization of variables to store the date and time
Take date input from the user in the form of string
if date is not of july and june
    print appropriate error message and exit
else
    Take sunrise and sunset time input from the user
    if sunrise time > sunset time
         print appropriate error message and exit
    else
        calculate the difference of sunset and sunrise times
        use the formula to calculate power
        power = number of cell * area of each cell * power generated by each cell * sun time * efficiency
        Income generated = power * .90

*/

public class Task2 {
    // this function takes a particular day and month as input and check if the date is of the month of june or july
    public boolean dateCheck(int mm, int dd)
    {
        if(mm == 6){
           if(dd >= 1 && dd <= 30){
               return true;
           }
        }
        else if(mm == 7){
            if(dd >= 1 && dd <= 31){
                return true;
            }
        }
        return false;
    }
    // this function checks if the time of sunrise < time of sunset, it returns true in this case. Otherwise it returns false
    public boolean timeCheck(int hhSunrise, int mmSunrise, int hhSunset, int mmSunset)
    {
        if(hhSunrise < hhSunset)
        {
            return true;
        }
        else if(hhSunrise == hhSunset)
        {
            if(mmSunset > mmSunrise)
            {
                return true;
            }
        }
        return false;
    }
    // this functions takes two different times as input and calculate different between the times in hours
    public float timeCalculate(int hhSunrise, int mmSunrise, int hhSunset, int mmSunset)
    {
        float hhDif;
        if(mmSunrise<= mmSunset)
            hhDif = hhSunset - hhSunrise;
        else
            hhDif = hhSunset - hhSunrise - 1;
        float mm =  (60 - mmSunrise) + mmSunset;
        if(mm > 60)
        {
            hhDif++;
            mm = mm %60;
        }
        return hhDif + (mm/60);
    }
    public static void main(String[] args) {

        Scanner Scan = new Scanner(System.in);
        Task2 t = new Task2();
        String date;
        String dateArr[] ;
        System.out.println("Write today's date [mm-dd]");
        date = Scan.nextLine(); // reading the next line entered by the user
        dateArr = date.split("-");
        int mm = Integer.parseInt(dateArr[0]); // converting string to int and storing it in mm
        int dd = Integer.parseInt(dateArr[1]); // converting string to int and storing it in hh
        if(!t.dateCheck(mm, dd))
        {
            System.out.println("Wrong date entered. Quitting the program");
        }
        else
        {
            String sunrise;
            String sunriseArr[];
            System.out.println("Enter time sunrise [hh: mm]>");
            sunrise = Scan.nextLine(); // reading the input
            sunriseArr = sunrise.split(":");
            int hhSunrise = Integer.parseInt(sunriseArr[0]); // converting string to int
            int mmSunrise = Integer.parseInt(sunriseArr[1]);

            String sunset;
            String sunsetArr[];
            System.out.println("Enter time sunset [hh: mm]>");
            sunset = Scan.nextLine();
            sunsetArr = sunset.split(":");
            int hhsunset = Integer.parseInt(sunsetArr[0]);
            int mmsunset = Integer.parseInt(sunsetArr[1]);
            float time;

            if(t.timeCheck(hhSunrise, mmSunrise, hhsunset,mmsunset)) // this checks if the time is valid
            {
                time = t.timeCalculate(hhSunrise, mmSunrise, hhsunset,mmsunset); // this calculates the difference in hours of two times

                double SolarPower = 0.20 * time * 1.7 *26 * 166; // calculating solar power
                SolarPower = SolarPower / 1000;
                System.out.printf("The production %s will be: %.2f kWh to a value of: SEK %.2f",date, SolarPower, .90*SolarPower);
            }
            else
            {
                System.out.printf("Invalid Time Entered: Quitting the program \n");
            }

        }
    }
}
